[IMP] impakta: Welcome sale_order_report_product_image
Vauxoo/impakta pull request #2
Opened 2024-10-04 21:11 UTC by JoseIbarraHdz

The module sale order report product image is now working on v17.

2024-10-04 22:26 UTC, edy1192 requested changes

2024-10-04 22:26 UTC, edy1192 commented on .gitmodules
> +	branch = 17.0-task-81483-JoseIbarraHdz
This must be the stable branch (17.0) please.

2024-11-04 23:45 UTC, edy1192 approved these changes

2024-12-09 19:17 UTC, JoseIbarraHdz commented
Hi @hugho-ad Edy approved the changes and the client give us the VoBo to merge, can you merge the PR please?

2024-12-09 19:21 UTC, hugho-ad commented
@JesusValdez96 

validates with the requested these changes, when can we do the release changes to production please

2024-12-09 19:22 UTC, hugho-ad commented
@JoseIbarraHdz sorry, not  @JesusValdez96

2024-12-10 00:10 UTC, merged